### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by matthewhall78** [bcgov/tfrs#99]
- [ ] Roles for Gov
- [ ] Roles for Fuel Suppliers
- [ ] Permissions for Gov
- [ ] Permissions for Fuel Suppliers

**Comment by kuanfandevops** [comment]
The issue was create for experimental use. We start to actively use the issues and milestones. Close this issue for now and reopen it if needed.
